### ISSUE TITLE
Problem with ODE dimension more than 1

### ISSUE THREAD

**Issue by Pier123456** [wgreene310/pde1dM#6]
I tried to run your example code diffusionTwoTanks.m

Here it's the error given by Matlab : 
Index exceeds the number of array elements. Index must not exceed 1.

Error in untitled>odeFunc (line 54)
F=[vdot(1)+f(1) vdot(2)+f(2)];

It seems the problem is coming to the coupled ODE equation. If the dimension of the ODE function F is more than 1 it doesn't work. 

Best regards,
PB

**Comment by Pier123456** [comment]
Sorry I had an old version of the code.

Great job BTW !

**Comment by wgreene310** [comment]
Thanks for reporting the problem.

Bill

**Comment by Pier123456** [comment]
I found maybe an issue. Have you an example function in which you use more than 1 dimension (m=1 or m=2) ? Because in my code, the conservation law (that I checked to be sure my problem was well written) are OK for m=0 but not for m=1 and m=2.

Cheers,
PB

**Comment by wgreene310** [comment]
Does this have anything to do with the diffusionTwoTanks example?

If not, please create a new issue, provide a complete description of the problem you are trying to solve, and attach your example code.
