### ISSUE TITLE
dimension m=1 or m=2

### ISSUE THREAD

**Issue by Pier123456** [wgreene310/pde1dM#7]
I found maybe an issue. Have you an example function in which you use more than 1 dimension (m=1 or m=2) ? Because in my code, the conservation law (that I checked to be sure my problem was well written) are OK for m=0 but not for m=1 and m=2.

Cheers,
PB

**Comment by wgreene310** [comment]
These cases have been tested.

As I said, if you believe you have found an error, provide a complete description, and attach your code.

**Comment by Pier123456** [comment]
It's my bad sorry (the conservation law works in the end)
